// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CQRSDemo.Models;

public partial class Student
{
    public int Id { get; set; }

    public string StudentName { get; set; }

    public string StudentEmail { get; set; }

    public string StudentAddress { get; set; }

    public int? StudentAge { get; set; }
}